// Reads scripts/.titles.json ([{id, title}]) and emits a SQL batch UPDATE to
// scripts/.backfill.sql, classifying each title via the shared classifier.
//
// Run with: pnpm dlx tsx scripts/emit-backfill-sql.ts
//
// Hardening notes:
//   - id is validated as a UUID before interpolation. Without this, a typo'd
//     id (or a hostile .titles.json) could inject SQL via the emitted file.
//   - category/programme are validated against the known enum sets. The
//     classifier's compile-time return type does not protect us if
//     .titles.json was generated by an older classifier or hand-edited.
//   - Output path is resolved relative to this script, not CWD. Running from
//     scripts/ used to silently fail to locate .titles.json.
//   - Only rows whose classification changes get emitted -- vs the previous
//     "write update for every row" behavior, which bumped updated_at on the
//     whole table and wrecked "what changed recently" telemetry.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { classify } from '../supabase/functions/_shared/classify';

const HERE = dirname(fileURLToPath(import.meta.url));
const INPUT = resolve(HERE, '.titles.json');
const OUTPUT = resolve(HERE, '.backfill.sql');

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

// Mirror of the DB enums (see supabase/migrations/0001 + 0004). Keep in sync.
const ROLE_CATEGORIES = new Set([
  'investment_banking',
  'sales_trading',
  'asset_management',
  'private_equity',
  'hedge_fund',
  'private_credit',
  'wealth_management',
  'research',
  'risk',
  'quant',
  'other',
  'risk_compliance',
  'technology',
  'corporate_functions',
]);
const PROGRAMMES = new Set([
  'spring_week',
  'summer_internship',
  'off_cycle_internship',
  'industrial_placement',
  'graduate',
  'experienced',
  'unknown',
]);

interface InputRow {
  id: string;
  title: string;
  category?: string;
  programme?: string;
}

const rows: InputRow[] = JSON.parse(readFileSync(INPUT, 'utf8'));

const valuesLines: string[] = [];
const counts: Record<string, number> = {};
let invalidIds = 0;
let unchanged = 0;
let unknownEnum = 0;

for (const r of rows) {
  if (!UUID_RE.test(r.id)) {
    invalidIds += 1;
    continue;
  }
  const { category, programme } = classify(r.title);
  if (!ROLE_CATEGORIES.has(category) || !PROGRAMMES.has(programme)) {
    unknownEnum += 1;
    continue;
  }
  // If the caller supplied the current DB values, skip unchanged rows so we
  // don't bump updated_at for no-op updates. When absent, emit anyway.
  if (
    r.category !== undefined &&
    r.programme !== undefined &&
    r.category === category &&
    r.programme === programme
  ) {
    unchanged += 1;
    continue;
  }
  valuesLines.push(`('${r.id}'::uuid, '${category}'::role_category, '${programme}'::programme_type)`);
  counts[category] = (counts[category] ?? 0) + 1;
}

if (valuesLines.length === 0) {
  console.log(`No rows to update. invalidIds=${invalidIds} unchanged=${unchanged} unknownEnum=${unknownEnum}`);
  writeFileSync(OUTPUT, '-- No updates required.\n');
  process.exit(0);
}

const sql = `-- Generated by scripts/emit-backfill-sql.ts. Do not edit by hand.
-- Rows: ${valuesLines.length}. Skipped: invalidIds=${invalidIds} unchanged=${unchanged} unknownEnum=${unknownEnum}.
update jobs set category = v.category, programme = v.programme
from (values
  ${valuesLines.join(',\n  ')}
) as v(id, category, programme)
where jobs.id = v.id
  and (jobs.category is distinct from v.category or jobs.programme is distinct from v.programme);
`;

writeFileSync(OUTPUT, sql);
console.log(`Wrote ${OUTPUT} with ${valuesLines.length} rows.`);
if (invalidIds > 0) console.warn(`  skipped ${invalidIds} rows with non-UUID id`);
if (unknownEnum > 0) console.warn(`  skipped ${unknownEnum} rows with classifier output outside the DB enum`);
if (unchanged > 0) console.log(`  skipped ${unchanged} rows unchanged`);
console.log('Category distribution:');
for (const [cat, n] of Object.entries(counts).sort((a, b) => b[1] - a[1])) {
  console.log(`  ${cat.padEnd(22)} ${n}`);
}
